<?php
require 'model/dbfunctions.php';

//check priviliges for sudo
if (!isset($_SESSION['staffid']) || $_SESSION['role'] != 'sudo') {
	header("location:restricted.php");
	die('No appropriate rights to access the file');
}



$conn = dbconnect();

$idno = $_GET['idno'];

if ($conn) {

	$sql = "UPDATE stafftable SET state = 1 WHERE idnumber = \"$idno\"";
	adddata($conn,$sql);



		require 'model/logsys.php';

		$details = "Previously Suspended staff resumed to Service";
		logSystem($conn,$details);

		

	$sql = "SELECT email from stafftable WHERE idnumber = \"$idno\"";
	$email = fetchdata($conn,$sql);
	$email = $email[0];
	$email = $email['email'];


	$mailbody = <<<EOT
		<div style="text-align:center; color:#009933; font-family:Times New Roman;  font-size:20px; border: solid 1px #009933; width:400px; padding:3px 3px 3px 3px;">
			<h2 style="color:#009900; font-family:Times New Roman; background-color:#f5f5f5; margin-top:0px; padding:3px 3px 3px 3px;;">Congratulations! <br> Your Account is now active.</h2>
			<p><a href="#"><img src="./images/komis.png" width="150" height="150"></a></p>
			<p>Hello . Your account is now fully operational once again. </p>
			<div style="text-align:left">
				
				<p>You can login <a href="stafflogin.php">here</a>.</p>
				<br><br>
				<p>Kind Regard,</p>
				<p>KOMIS</p>
			</div>

			
			<p style="color:#993333">This email was autogenerated. Do not reply</p>
		
			<h3 style="color:#009933; font-family:Times New Roman; background-color:#f5f5f5; margin-bottom:0px; padding-top:0px 0px 0px 0px;">KOMIS</h3>
		</div>
EOT;
					$mailsubject = "Account resumption to service.";
					$to = $email;
					$headers = "MIME-Version: 1.0" . "\r\n";
					$headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";
					$headers .= "no-reply@komis.com". "\r\n";

					//echo "To: $email <br> $mailbody";
					mail($to,$mailsubject,$mailbody,$headers);


		// $detail = "$idno was resumed to service by the admin";
		// logsys($conn,$detail);
		//header("Location:suspendstaff.php");


}else{
	die('Error while connecting.');
}
?>